version: '2'
services:
  php:
    container_name: event
    build:
      context: ./docker/dockerfiles/php
    working_dir: /var/www
    volumes:
    - ./code:/var/www/html
    - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
    links:
    - db
    ports:
    - 9002:9000
  web:
    container_name: nginx
    image: nginx:1.15
    volumes:
    - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
    - php
    links:
    - php
    ports:
    - 8080:80
  db:
    container_name: pgsql
    image: postgres:9.5
    volumes:
    - ./docker/dbdata:/var/lib/postgresql/data
    environment:
    - "POSTGRES_USER=event"
    - "POSTGRES_PASSWORD=event"
    ports:
    - 54321:5432